export {default as Home} from './home/Home'
export {default as About} from './about/About'
export {default as Contact} from './contact/Contact'
export {default as Error} from './error/Error'
export {default as LogIn} from './login/Login'
